# coding: utf-8
from pydantic import BaseModel

class m_APPO_D(BaseModel):
    VoucherID: str
    NoDet: str
    DType: str
    Account: str
    DivID: str
    Tax: int
    Tax1: int
    RefVou: str
    RefNO: str
    RefMainDoc: str
    RefPreDoc: str
    RefDetailDoc: str
    RefOthDoc: str
    TranDocD: str
    RefD1: str
    RefD2: str
    MerkID: str
    ThingType: str
    ThingID: str
    SerialID: str
    Descript: str
    Qty: str
    UnitID: str
    UnitPrice: str
    DiscAmount: str
    RefCur: str
    RefAmount: str
    Rate: str
    AmountD: str
    BalanceD: str
    TaxAmount: int
    TaxAmount1: int
    OthCost: str

class m_APPO_H(BaseModel):
    VoucherID: str
    Account: str
    Cur: str
    DateDay: str
    DateDue: str
    TType: str
    PartnerName: str
    PartnerID: str
    Receiver: str
    MainDoc: str
    PreDoc: str
    DetailDoc: str
    OthDoc: str
    TranDoc: str
    Ref1: str
    Ref2: str
    TotalDiscount: str
    TotalTax: str
    TotalTax1: str
    SubTotal: str
    GrandTotal: str
    BalanceH: str
    TotalAdj: str
    TotalCost: str
    Journal: str
    RateJou: str
    Paid: str
    HeadJou: str
    UserID: str
    DateEntry: str
    DateUpdate: str
    UserLock: str
    AddDesc: str

class m_APProduct(BaseModel):
    Item_ID_NV: str
    Item_Desc_NV: str
    Item_Acc_NV: str

class m_APVou_D(BaseModel):
    VoucherID: str
    NoDet: str
    DType: str
    Account: str
    DivID: str
    Tax: sint
    Tax1: int
    RefVou: str
    RefNO: str
    RefMainDoc: str
    RefPreDoc: str
    RefDetailDoc: str
    RefOthDoc: str
    TranDocD: str
    RefD1: str
    RefD2: str
    MerkID: str
    ThingType: str
    ThingID: str
    SerialID: str
    Descript: str
    Qty: str
    UnitID: str
    UnitPrice: str
    DiscAmount: str
    RefCur: str
    RefAmount: str
    Rate: str
    AmountD: str
    BalanceD: str
    TaxAmount: int
    TaxAmount1: int
    OthCost: str

class m_APVou_D1(BaseModel):
    VoucherID: str
    NoDet: str
    DType1: str
    Account1: str
    RefVou1: str
    RefNO1: str
    RefMainDoc1: str
    RefPreDoc1: str
    RefDetailDoc1: str
    RefOthDoc1: str
    TranDocD1: str
    RefD11: str
    RefD21: str
    MerkID1: str
    ThingType1: str
    ThingID1: str
    SerialID1: str
    Descript1: str
    Qty1: str
    UnitID1: str
    UnitPrice1: str
    DiscAmount1: str
    RefCur1: str
    RefAmount1: str
    Rate1: str
    AmountD1: str
    BalanceD1: str
    TaxAmount1: int
    TaxAmount11: int
    OthCost1: str

class m_APVou_H(BaseModel):
    VoucherID: str
    Account: str
    Cur: str
    DateDay: str
    DateDue: str
    TType: str
    PartnerName: str
    PartnerID: str
    Receiver: str
    MainDoc: str
    PreDoc: str
    DetailDoc: str
    OthDoc: str
    TranDoc: str
    Ref1: str
    Ref2: str
    TotalDiscount: str
    TotalTax: str
    TotalTax1: str
    SubTotal: str
    GrandTotal: str
    BalanceH: str
    TotalAdj: str
    TotalCost: str
    Journal: str
    RateJou: str
    Paid: str
    HeadJou: str
    UserID: str
    DateEntry: str
    DateUpdate: str
    UserLock: str
    AddDesc: str

class m_APVou_H1(BaseModel):
    VoucherID: str
    POno: str
    PODate: str
    MainDoc1: str
    PreDoc1: str
    DetailDoc1: str
    OthDoc1: str
    Ref11: str
    Ref21: str
    TotalTax1: str
    TotalTax11: str
    GrandTotal1: str
    BalanceH1: str
    Paid1: str

class m_ARVou_D(BaseModel):
    VoucherID: str
    NoDet: str
    DType: str
    Account: str
    DivID: str
    Tax: sint
    Tax1: int
    RefVou: str
    RefNO: str
    RefMainDoc: str
    RefPreDoc: str
    RefDetailDoc: str
    RefOthDoc: str
    TranDocD: str
    RefD1: str
    RefD2: str
    MerkID: str
    ThingType: str
    ThingID: str
    SerialID: str
    Descript: str
    Qty: str
    UnitID: str
    UnitPrice: str
    DiscAmount: str
    RefCur: str
    RefAmount: str
    Rate: str
    AmountD: str
    BalanceD: str
    TaxAmount: int
    TaxAmount1: int
    OthCost: str

class m_ARVou_D1(BaseModel):
    VoucherID: str
    NoDet: str
    DType1: str
    Account1: str
    RefVou1: str
    RefNO1: str
    RefMainDoc1: str
    RefPreDoc1: str
    RefDetailDoc1: str
    RefOthDoc1: str
    TranDocD1: str
    RefD11: str
    RefD21: str
    MerkID1: str
    ThingType1: str
    ThingID1: str
    SerialID1: str
    Descript1: str
    Qty1: str
    UnitID1: str
    UnitPrice1: str
    DiscAmount1: str
    RefCur1: str
    RefAmount1: str
    Rate1: str
    AmountD1: str
    BalanceD1: str
    TaxAmount1: int
    TaxAmount11: int
    OthCost1: str

class m_ARVou_H(BaseModel):
    VoucherID: str
    Account: str
    Cur: str
    DateDay: str
    DateDue: str
    TType: str
    PartnerName: str
    PartnerID: str
    Receiver: str
    MainDoc: str
    PreDoc: str
    DetailDoc: str
    OthDoc: str
    TranDoc: str
    Ref1: str
    Ref2: str
    TotalDiscount: str
    TotalTax: str
    TotalTax1: str
    SubTotal: str
    GrandTotal: str
    BalanceH: str
    TotalAdj: str
    TotalCost: str
    Journal: str
    RateJou: str
    Paid: str
    HeadJou: str
    UserID: str
    DateEntry: str
    DateUpdate: str
    UserLock: str
    AddDesc: str

class m_ARVou_H1(BaseModel):
    VoucherID: str
    POno: str
    PODate: str
    MainDoc1: str
    PreDoc1: str
    DetailDoc1: str
    OthDoc1: str
    Ref11: str
    Ref21: str
    TotalTax1: str
    TotalTax11: str
    GrandTotal1: str
    BalanceH1: str
    Paid1: str

class m_Asset(BaseModel):
    OffCode: str
    AssetID: str
    Name: str
    AssetKindID: str

class m_AssetKind(BaseModel):
    AssetKindID: str
    Name: str

class m_Bhs(BaseModel):
    captText: str
    bhsID: str
    ShowText: str

class m_BranchOffice(BaseModel):
    OffCode: str
    CompanyID: str
    CityID: str
    name: str

class m_CBAdv_D(BaseModel):
    VoucherID: str
    NoDet: str
    DType: str
    Account: str
    DivID: str
    Tax: sint
    Tax1: int
    RefVou: str
    RefNO: str
    RefMainDoc: str
    RefPreDoc: str
    RefDetailDoc: str
    RefOthDoc: str
    TranDocD: str
    RefD1: str
    RefD2: str
    MerkID: str
    ThingType: str
    ThingID: str
    SerialID: str
    Descript: str
    Qty: str
    UnitID: str
    UnitPrice: str
    DiscAmount: str
    RefCur: str
    RefAmount: str
    Rate: str
    AmountD: str
    BalanceD: str
    TaxAmount: int
    TaxAmount1: int
    OthCost: str

class m_CBAdv_D1(BaseModel):
    VoucherID: str
    NoDet: str
    DType1: str
    Account1: str
    RefVou1: str
    RefNO1: str
    RefMainDoc1: str
    RefPreDoc1: str
    RefDetailDoc1: str
    RefOthDoc1: str
    TranDocD1: str
    RefD11: str
    RefD21: str
    MerkID1: str
    ThingType1: str
    ThingID1: str
    SerialID1: str
    Descript1: str
    Qty1: str
    UnitID1: str
    UnitPrice1: str
    DiscAmount1: str
    RefCur1: str
    RefAmount1: str
    Rate1: str
    AmountD1: str
    BalanceD1: str
    TaxAmount1: int
    TaxAmount11: int
    OthCost1: str

class m_CBAdv_H(BaseModel):
    VoucherID: str
    Account: str
    Cur: str
    DateDay: str
    DateDue: str
    TType: str
    PartnerName: str
    PartnerID: str
    Receiver: str
    MainDoc: str
    PreDoc: str
    DetailDoc: str
    OthDoc: str
    TranDoc: str
    Ref1: str
    Ref2: str
    TotalDiscount: str
    TotalTax: str
    TotalTax1: str
    SubTotal: str
    GrandTotal: str
    BalanceH: str
    TotalAdj: str
    TotalCost: str
    Journal: str
    RateJou: str
    Paid: str
    HeadJou: str
    UserID: str
    DateEntry: str
    DateUpdate: str
    UserLock: str
    AddDesc: str

class m_CBBalance(BaseModel):
    ThingId: str
    PeriodID: str
    Out: str
    In: str
    BegBalance: str
    EndBalance: str

class m_CBVou_D(BaseModel):
    VoucherID: str
    NoDet: str
    DType: str
    Account: str
    DivID: str
    Tax: sint
    Tax1: int
    RefVou: str
    RefNO: str
    RefMainDoc: str
    RefPreDoc: str
    RefDetailDoc: str
    RefOthDoc: str
    TranDocD: str
    RefD1: str
    RefD2: str
    MerkID: str
    ThingType: str
    ThingID: str
    SerialID: str
    Descript: str
    Qty: str
    UnitID: str
    UnitPrice: str
    DiscAmount: str
    RefCur: str
    RefAmount: str
    Rate: str
    AmountD: str
    BalanceD: str
    TaxAmount: int
    TaxAmount1: int
    OthCost: str

class m_CBVou_D1(BaseModel):
    VoucherID: str
    NoDet: str
    DType1: str
    Account1: str
    RefVou1: str
    RefNO1: str
    RefMainDoc1: str
    RefPreDoc1: str
    RefDetailDoc1: str
    RefOthDoc1: str
    TranDocD1: str
    RefD11: str
    RefD21: str
    MerkID1: str
    ThingType1: str
    ThingID1: str
    SerialID1: str
    Descript1: str
    Qty1: str
    UnitID1: str
    UnitPrice1: str
    DiscAmount1: str
    RefCur1: str
    RefAmount1: str
    Rate1: str
    AmountD1: str
    BalanceD1: str
    TaxAmount1: int
    TaxAmount11: int
    OthCost1: str

class m_CBVou_H(BaseModel):
    VoucherID: str
    Account: str
    Cur: str
    DateDay: str
    DateDue: str
    TType: str
    PartnerName: str
    PartnerID: str
    Receiver: str
    MainDoc: str
    PreDoc: str
    DetailDoc: str
    OthDoc: str
    TranDoc: str
    Ref1: str
    Ref2: str
    TotalDiscount: str
    TotalTax: str
    TotalTax1: str
    SubTotal: str
    GrandTotal: str
    BalanceH: str
    TotalAdj: str
    TotalCost: str
    Journal: str
    RateJou: str
    Paid: str
    HeadJou: str
    UserID: str
    DateEntry: str
    DateUpdate: str
    UserLock: str
    AddDesc: str

class m_Category(BaseModel):
    CategoryID: str
    CategoryDesc: str

class m_City(BaseModel):
    CityID: str
    Name: str
    countryID: str
    locKind: str

class m_Company(BaseModel):
    CompanyID: str
    CompanyName: str
    CompanyName1: str
    CompanyHead: str
    CompanyAddress: str
    CompanyPhone: str

class m_Country(BaseModel):
    CountryID: str
    Name: str

class m_Curency(BaseModel):
    Cur: str
    Name: str
    CountryID: str
    Rate: str
    Mark: str

class m_Customer(BaseModel):
    PartnerID: str
    PartnerName: str
    Ident: str
    OrgType: str
    Address1: str
    Address2: str
    Address3: str
    Address4: str
    CityID: str
    CountryID: str
    ZipCode: str
    Phone1: str
    Phone2: str
    Fax1: str
    Fax2: str
    Email: str
    Contact1: str
    Contact2: str
    NPWP: str
    NPWPdate: str
    NPWPKukuh: str
    NPWPdateKukuh: str
    NPWP1: str
    NPWPdate1: str
    NPWPKukuh1: str
    NPWPdateKukuh1: str
    APITU: str
    SPR: str
    SIUP: str
    Note1: str
    Note2: str
    CorAdd1: str
    CorAdd2: str
    CorAdd3: str
    CorAdd4: str
    CorCityID: str
    CorCountryID: str
    CorZipCode: str
    CorPhone1: str
    CorPhone2: str
    CorFax1: str
    CorFax2: str
    CorEmail: str
    CorContact1: str
    CorContact2: str
    Active: str
    UserID: str

class m_DType(BaseModel):
    DType: str
    Name: str
    CorVoucherType: str
    Modul: str
    HeadDC: str
    FoGroup: str

class m_DailyTranJob(BaseModel):
    ProductID: str
    name: str
    account: str
    GroupProdID: str
    AssetKind: str
    inv: str
    Emod: str
    Mmod: str
    Amod: str

class m_Department(BaseModel):
    DepartmentID: str
    DepartmentName: str
    DepartmentHead: str
    OffCode: str

class m_DetDemPeriod(BaseModel):
    DD_Period_ID_VC: str
    DD_Start_Day_SI: str
    DD_End_Day_SI: str
    DD_Desc_VC: str

class m_Division(BaseModel):
    OffCode: str
    DivID: str
    DivName: str

class m_Forex(BaseModel):
    ForexID: str
    ForexCode: str
    ForexDesc: str
    ForexCountryID: str

class m_GetDatetime(BaseModel):
    OffCode: str
    UserID: str
    datedaytime: str

class m_InvDesc(BaseModel):
    OffCode: str
    InvID: str
    JobKind: str
    InvType: str
    Account: str
    Tax: sint
    Tax1: int
    InvDesc: str

class m_Item(BaseModel):
    OffCode: str
    itemID: str
    InvID: str
    ItemDesc: str
    GroupItem: str
    Account: str
    Cur: str
    HrgStd: str

class m_JobKind(BaseModel):
    OffCode: str
    JobKind: str
    JobName: str
    DivID: str

class m_JobOrder(BaseModel):
    OffCode: str
    JobID: str
    JobKind: str
    DateDay: str
    Ident: str
    PartnerID: str
    PartnerName: str
    Descript: str
    CustomerName: str
    Weight: str
    Measurement: str
    Utility: str
    Dishpack: str
    Clothing: str
    Glass: str
    Furniture: str
    Comment: str
    AllPacker: str
    Packer: str
    Freelance: str
    ElfBox: str
    ElfBak: str
    LooseBak: str
    L300Box: str
    PickUp: str
    Panther: str
    LCLshipment: str
    WoodenLiftvan: str
    CartonLiftvan: str
    FCLshipment: str
    FCL20: str
    FCL40: str
    LoosePack: str
    Liftvan: str
    Departure: str
    PaymentType: str
    AddPay: str
    OrderByName: str
    OrderByDate: str
    CargoDivName: str
    CargoDivDate: str
    MPdivName: str
    MPdivDate: str
    Remark: str
    DateUpdate: str
    active: str

class m_JobOrderX(BaseModel):
    OffCode: str
    JobID: str
    JobKind: str
    DateDay: str
    Ident: str
    PartnerID: str
    PartnerName: str
    KindOfWork: str
    ShipConsignee: str
    NameOfGood: str
    CustomerRef: str
    LoadPort: str
    DischargePort: str
    VesselFlight: str
    ETA: str
    ETD: str
    ClearanceDate: str
    DeliveryDate: str
    BlAwbM: str
    BlAwbH: str
    Service: str
    ContSize: str
    ContainerNo: str
    QofGood: str
    Weight: str
    Measurement: str
    ShippingName: str
    WarehouseName: str
    TypeOfService: str
    EPTEBc23Peb30Date: str
    PTBc23Peb30: str
    PTPE: str
    PTInvoice: str
    PTPacking: str
    PTBlAwbAsli: str
    PTAsuransi: str
    PTSK: str
    PTKonlak: str
    PTSSBP: str
    GCPib20Peb30: str
    GCPE: str
    GCInvoice: str
    GCPacking: str
    GCBlAwbAsli: str
    GCSK: str
    GCSTTJ: str
    GCIzinDep: str
    GCCIS: str
    GCIP: str
    GCMaster: str
    GCNPIK: str
    GCSKBPPN: str
    GCAsuransi: str
    GCSSPCP: str
    Driver: str
    Truck: str
    Condition: str
    Remark: str
    active: str

class m_MaterialType(BaseModel):
    MateID: str
    MateDesc: str

class m_Menu(BaseModel):
    OffCode: str
    MenuId: str
    Name: str
    FrmName: str
    Remark: str
    UserUse: str

class m_Merk(BaseModel):
    MerkID: str
    Name: str
    Descript: str
    GroupMerk: str

class m_Paste_Errors(BaseModel):
    Field0: str

class m_PaySalesTran(BaseModel):
    PayID: str
    PayKindID: str
    PayDesc: str
    Account: str
    CostType: str
    Cost: str
    CostAccount: str
    Mark: str
    Active: str

class m_PaymentVoucher(BaseModel):
    VoucherID: str
    NoDet: str
    PayID: str
    IdentityNo: str
    IdentityName: str
    Amount: str
    OtherAmount: str
    Cost: str
    TotalPay: str
    BalanceD: str

class m_PeriodACC(BaseModel):
    PeriodID: str
    PeriodName: str
    StartDate: str
    EndDate: str
    YearPeriod: str
    CloseStat: str
    CloseDate: str
    UserID: str
    UserIDClose: str

class m_PeriodFO(BaseModel):
    OffCode: str
    PeriodID: str
    PeriodDate: str

class m_Port(BaseModel):
    PortCode_CH: str
    PortName_CH: str
    PortType_CH: str
    PortTrade_CH: str
    PortRate_NU: str
    PortCountry_CH: str
    CityID_CH: str
    LocKind: str

class m_PrincipalMain(BaseModel):
    Prin_Code_CH: str
    Prin_Name_CH: str
    Prin_Name1_CH: str
    Prin_Address1_CH: str
    Prin_Address2_CH: str
    Prin_Address3_CH: str
    Prin_Address4_CH: str
    Prin_Address5_CH: str
    Prin_City_CH: str
    Prin_Country_CH: str
    Prin_Zip_CH: str
    Prin_Phone_CH: str
    Prin_Fax_CH: str
    Prin_Email_CH: str
    Prin_Type_CH: str
    Prin_Inactive_BT: str
    Prin_UserID_CH: str
    Prin_BL_Code_CH: str
    Prin_KtrAs_CH: str

class m_ProductBuy(BaseModel):
    ProductID: str
    name: str
    account: str
    UnitPrice: str
    GroupProdID: str
    AssetKind: str
    inv: str
    Emod: str
    Mmod: str
    Amod: str

class m_ProductSale(BaseModel):
    ProductID: str
    name: str
    account: str
    Cur: str
    UnitPrice: str
    GroupProdID: str
    AssetKind: str
    inv: str
    Emod: str
    Mmod: str
    Amod: str

class m_Rate(BaseModel):
    Cur1: str
    Cur2: str
    RateAmount: str

class m_SaleVou_D(BaseModel):
    VoucherID: str
    NoDet: str
    DType: str
    Account: str
    DivID: str
    Tax: sint
    Tax1: int
    RefVou: str
    RefNO: str
    RefMainDoc: str
    RefPreDoc: str
    RefDetailDoc: str
    RefOthDoc: str
    TranDocD: str
    RefD1: str
    RefD2: str
    ThingType: str
    ThingID: str
    SerialID: str
    Descript: str
    Qty: str
    UnitID: str
    UnitPrice: str
    DiscAmount: str
    RefCur: str
    RefAmount: str
    Rate: str
    AmountD: str
    BalanceD: str
    TaxAmount: int
    TaxAmount1: int
    OthCost: str

class m_SaleVou_H(BaseModel):
    VoucherID: str
    Account: str
    Cur: str
    DateDay: str
    DateDue: str
    TType: str
    PartnerName: str
    PartnerID: str
    Receiver: str
    MainDoc: str
    PreDoc: str
    DetailDoc: str
    OthDoc: str
    TranDoc: str
    Ref1: str
    Ref2: str
    TotalDiscount: str
    TotalTax: str
    TotalTax1: str
    SubTotal: str
    GrandTotal: str
    BalanceH: str
    TotalAdj: str
    TotalCost: str
    Journal: str
    RateJou: str
    Paid: str
    HeadJou: str
    UserID: str
    DateEntry: str
    DateUpdate: str
    UserLock: str
    AddDesc: str

class m_Sales(BaseModel):
    OffCode: str
    SalesId: str
    Name: str
    Comm: str
    Active: str

class m_SetupSystem(BaseModel):
    OffCode: str
    Address1: str
    Address2: str
    Address3: str
    NPWP: str
    NPWPDate: str
    NPWPKukuh: str
    NPWPDateKukuh: str
    AccSubgroupPL: str
    AccountPLDitahan: str
    AccountPLBerJalan: str
    InvoiceName: str
    Tax1Name: str
    Tax1Title: str
    Name1: str
    Name2: str
    Name3: str
    TaxStd: int
    TaxSdn: int
    ARTaxAccount: str
    ARTax1Account: str
    SelisihAcckurs: str
    DiscountAcc: str
    userlock: str

class m_Supplier(BaseModel):
    PartnerID: str
    PartnerName: str
    Address1: str
    Address2: str
    Address3: str
    Address4: str
    CityID: str
    CountryID: str
    ZipCode: str
    Phone1: str
    Phone2: str
    Fax1: str
    Fax2: str
    Email: str
    Contact1: str
    Contact2: str
    NPWP: str
    NPWPdate: str
    NPWPdateKukuh: str
    Note1: str
    Note2: str
    CorAdd1: str
    CorAdd2: str
    CorAdd3: str
    CorAdd4: str
    CorCityID: str
    CorCountryID: str
    CorZipCode: str
    CorPhone1: str
    CorPhone2: str
    CorFax1: str
    CorFax2: str
    CorEmail: str
    CorContact1: str
    CorContact2: str
    Inactive: str
    UserID: str

class m_Tax(BaseModel):
    TaxID: int
    Name: str
    Amount: str

class m_TranMain(BaseModel):
    TranMain: str
    CompanyID: str
    BranchID: str
    DepartmentID: str

class m_TranType(BaseModel):
    TType: str
    Name: str
    CorVoucherType: str
    Modul: str
    HeadDC: str
    FoGroup: str

class m_Unit(BaseModel):
    UnitID: str
    Name: str

class m_UserGroupMain(BaseModel):
    OffCode: str
    UserGroupId: str
    UserGroupName: str
    Modul: str

class m_UserGroupMenuButton(BaseModel):
    OffCode: str
    UserGroupId: str
    MenuId: str
    UserGroupName: str
    bOpen: str
    bAdd: str
    bEdit: str
    bDelete: str
    bPrint: str

class m_UserMain(BaseModel):
    OffCode: str
    UserId: str
    UserGroupId: str
    UserName: str
    UserRank: str
    UserLogon: str
    UserLastLogon: str
    UserSpecial: str
    UserPassword: str
    DeptID: str
    UserDateInp: str
    UserIDInp: str
    Active: str

class m_Vendor(BaseModel):
    PartnerID: str
    PartnerName: str
    Ident: str
    OrgType: str
    Customer: str
    Vendor: str
    Principal: str
    Address1: str
    Address2: str
    Address3: str
    Address4: str
    CityID: str
    CountryID: str
    ZipCode: str
    Phone1: str
    Phone2: str
    Fax1: str
    Fax2: str
    Email: str
    Contact1: str
    Contact2: str
    NPWP: str
    NPWPdate: str
    NPWPKukuh: str
    NPWPdateKukuh: str
    NPWP1: str
    NPWPdate1: str
    NPWPKukuh1: str
    NPWPdateKukuh1: str
    APITU: str
    SPR: str
    SIUP: str
    Note1: str
    Note2: str
    CorAdd1: str
    CorAdd2: str
    CorAdd3: str
    CorAdd4: str
    CorCityID: str
    CorCountryID: str
    CorZipCode: str
    CorPhone1: str
    CorPhone2: str
    CorFax1: str
    CorFax2: str
    CorEmail: str
    CorContact1: str
    CorContact2: str
    Active: str
    UserID: str

class m_gLen(BaseModel):
    gNumber: str
    gLenThing: str
    gLenVoucher: str
    gLenOffCode: str
    gLenCounter: str
    gLenTranID: str
    gMCounter: str
    gLenAccount: str

